name: E2E Latest

on:
  push:
  pull_request:

env:
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

jobs:
  run-e2e-test:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run e2e test
        run: yarn test:e2e:latest
